smi_id_min: 0
smi_id_max: 800
dataset: "zinc"
dataset_path: "main/gegl/resource/data/zinc/logp_800.txt"
max_smiles_length: 120
similarity_threshold: 0.4
apprentice_load_dir: "main/gegl/resource/checkpoint/zinc"
learning_rate: 0.001
sample_batch_size: 512
optimize_batch_size: 256
mutation_rate: 0.01
num_steps: 50
num_keep: 1024
max_sampling_batch_size: 1024
apprentice_sampling_batch_size: 1024
expert_sampling_batch_size: 1024
apprentice_training_batch_size: 256
num_apprentice_training_steps: 4
num_jobs: 8
record_filtered: True 
use_atomrings: True